-- Phase 2F.4: analytics date/filter indexes. No UTM, no snapshot, no TimelineEvent.
CREATE INDEX "Lead_createdAt_idx" ON "Lead"("createdAt");
CREATE INDEX "Lead_status_idx" ON "Lead"("status");
CREATE INDEX "Lead_serviceId_idx" ON "Lead"("serviceId");
CREATE INDEX "Lead_locationId_idx" ON "Lead"("locationId");
CREATE INDEX "Quote_createdAt_idx" ON "Quote"("createdAt");
CREATE INDEX "Quote_status_idx" ON "Quote"("status");
CREATE INDEX "Quote_serviceId_idx" ON "Quote"("serviceId");
CREATE INDEX "Quote_locationId_idx" ON "Quote"("locationId");
CREATE INDEX "Invoice_createdAt_idx" ON "Invoice"("createdAt");
CREATE INDEX "Invoice_updatedAt_idx" ON "Invoice"("updatedAt");
CREATE INDEX "Invoice_status_idx" ON "Invoice"("status");
CREATE INDEX "Booking_supervisorId_idx" ON "Booking"("supervisorId");
CREATE INDEX "Booking_createdAt_idx" ON "Booking"("createdAt");
CREATE INDEX "Booking_updatedAt_idx" ON "Booking"("updatedAt");
CREATE INDEX "Booking_status_idx" ON "Booking"("status");
CREATE INDEX "Booking_type_idx" ON "Booking"("type");
CREATE INDEX "Booking_serviceId_idx" ON "Booking"("serviceId");
CREATE INDEX "Booking_locationId_idx" ON "Booking"("locationId");
CREATE INDEX "WorkOrder_supervisorId_idx" ON "WorkOrder"("supervisorId");
CREATE INDEX "WorkOrder_createdAt_idx" ON "WorkOrder"("createdAt");
CREATE INDEX "WorkOrder_updatedAt_idx" ON "WorkOrder"("updatedAt");
CREATE INDEX "WorkOrder_status_idx" ON "WorkOrder"("status");
CREATE INDEX "AmcContract_endDate_idx" ON "AmcContract"("endDate");
CREATE INDEX "Review_createdAt_idx" ON "Review"("createdAt");
CREATE INDEX "Review_type_status_idx" ON "Review"("type", "status");
